name: PR Checks

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.0', '2.7']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Start backing services
        run: docker-compose up -d
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Wait for services to come up
        run: sleep 3
      - name: Run specs
        run: bundle exec rspec spec/
